export const NEW_BOOKING_REQUEST = "NEW_BOOKING_REQUEST";
export const NEW_BOOKING_SUCCESS = "NEW_BOOKING_SUCCESS";
export const NEW_BOOKING_FAIL = "NEW_BOOKING_FAIL";

export const MY_BOOKINGS_REQUEST = "MY_BOOKINGS_REQUEST";
export const MY_BOOKINGS_SUCCESS = "MY_BOOKINGS_SUCCESS";
export const MY_BOOKINGS_FAIL = "MY_BOOKINGS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
