export const ALL_CLASS_REQUEST = "ALL_CLASS_REQUEST";
export const ALL_CLASS_SUCCESS = "ALL_CLASS_SUCCESS";
export const ALL_CLASS_FAIL = "ALL_CLASS_FAIL";

export const CLASS_DETAILS_REQUEST = "CLASS_DETAILS_REQUEST";
export const CLASS_DETAILS_SUCCESS = "CLASS_DETAILS_SUCCESS";
export const CLASS_DETAILS_FAIL = "CLASS_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
